// IR Sensors
#define irOne 2 
#define irTwo 3
#define irThree 4
#define irFour 10
#define irFive 11
#define irSix 45
#define irSeven 46
#define irEight 14
#define irNine 15
#define irTen 16
#define irEleven 17
#define irTwelve 18
#define irThirteen 19
#define irFourteen 20 
#define irFifteen 21
#define irSixteen 22
#define irSeventeen 23
#define irEighteen 24
#define irNineteen 25
#define irTwenty 26
#define irTwentyOne 29
#define irTwentyTwo 32
#define irTwentyThree 33
#define irTwentyFour 38

